### PR TITLE
h264 support

### PR DESCRIPTION
**Pull request by KLFrost**
currently the new binaries are stored in the bucket at `ffmpeg.2.tar.gz`, etc.

### CODE REVIEW

**Comment by toddgardner** [comment]
To do other videos we'll need AAC at least for the audio, but just for gifs this is fine.

:+1:

**Comment by toddgardner** [comment]
Oh, if the URL is different, you'll need to point the buildpack compile at the new binaries

**Comment by KLFrost** [comment]
I was thinking I'd just copy the new binaries over the old ones in the bucket, but actually, I think it's a better convention to change the path name, so I'll patch this PR with the new path.

**Comment by JoeEnnever** [comment]
Do we still need this?

**Comment by KLFrost** [comment]
i started setting this up for a future where we may want to process `gif => video` or user-uploaded videos... but i don't think it's urgent.

**Pull request merged**
